### ISSUE TITLE
Support for special .github repository

### ISSUE THREAD

**Issue by bkeepers** [probot/probot-config#1]
One of the ideas a few people have been kicking around in the @probot community and within GitHub is the idea of treating a repository named `.github` as a special org-wide configuration repository.

https://github.com/probot/stale/pull/106 switches the stale app to using this extension to start experimenting with this idea, and I created https://github.com/probot/.github to store the configs.

I also wanted to propose some changes to this extension that would treat `.github` uniquely:

1. If a user does `_extends: .github`, then read the file out of the root of that repository instead of a `.github` directory within that repository. For example, right now I had to put the configs in https://github.com/probot/.github/tree/master/.github to make it work.

2. Maybe even consider _also_ looking in `.github` automatically. This will double the number of API requests for looking up config files, but would make make the `.github` repository a convention across probot apps.

Thoughts?

cc @jasonetco @hiimbex

**Comment by hiimbex** [comment]
👍 I think this would be a great option for larger orgs, where the `.github` folder in every repo takes up space. It creates a nice repo for discussing org level administrative issues and the like. I think it is a powerful precedent to set, but obviously with the existing support.

**Comment by itaditya** [comment]
I also love this idea

**Comment by cco3** [comment]
I'm a fan of these ideas.  In addition to the benefit for larger orgs, there are also projects that largely act as mirrors, where it is undesirable to change the upstream repo just to configure an app the runs on the mirror.

For 2, is the idea that all configs would, by default, extend org/.github?  (That would make sense to me)

**Comment by dessant** [comment]
How will single file permissions work when a config file extends from the `.github` repo? Wouldn't it fail when accessing the config from the repo root?

**Comment by dessant** [comment]
For example, the `stale` app requests read-only access for the `.github/stale.yml` file path. Let's suppose the app is installed for the `.github` and `test` repo.

Accessing the config in the `test` repo will work as expected, but the current implementation will look for the `stale.yml` file path in the `.github` repo, when the config is not present in the `test` repo, or when we explicitly set the `.github` repo for the `_extends` config option. The config path that we extend from could also be set to anything else by users.

https://github.com/probot/probot-config/blob/def82e6b324439f08c1c630c4f3cb57bab689979/README.md#L44-L74

It looks like you can access the config files regardless of the single file permission if the repository is public, so the single file permission likely comes into play for private repos, though I'm not able to test that part :yum:.

It seems we would need to request read-only access to repository contents just to read the config files, or we would need to require that the `.github` repo (and any other repo where a custom `_extends` path is pointed to) be public.

This is easy to control in internal/self-deployed apps, but can lead to confusion during the use of a hosted app that works with probot-config.

Config file access could be explained in the README, so any app using probot-config can link to it from their own config/docs.

**Comment by gr2m** [comment]
I think this issue can be closed, but I would suggest to create a follow up issue regarding [@dessant comment](https://github.com/probot/probot-config/issues/1#issuecomment-399650687)

> How will single file permissions work when a config file extends from the .github repo? Wouldn't it fail when accessing the config from the repo root?

My assumption is that if the `.github` repo is private and the app has only single file access like `.github/my-app.yml` then it will fail

**Comment by z-hirschtritt** [comment]
Are we planning on cutting a release for this change?

**Comment by nesl247** [comment]
I think it makes more sense to make even the .github repo require `.github/` instead of at the root level. It solves this for both public and private repos, and reduces the API load. Maybe deprecate the old behavior and do it as a fallback.

**Comment by bkeepers** [comment]
0.2.0 has been released with this feature. Huge 👏 to @cco3 for working on this, and @hiimbex for giving feedback and review.

**Comment by nesl247** [comment]
@bkeepers Should we open another issue then given that this does not work well for private repos?

**Comment by dessant** [comment]
@nesl247, yes, though we could just document the limitation instead of reverting.

**Comment by nesl247** [comment]
I've opened #13 to discuss it.
