### ISSUE TITLE
Private base repo stop bots from using single file permission

### ISSUE THREAD

**Issue by nesl247** [probot/probot-config#13]
When you have the `.github` repository, and a bot requires a single file `.github/stale.yml`, probot-config does not work with the `.github` directory because it requires the files to be in the root instead of the same path.

This was caused with #6

**Comment by dessant** [comment]
The issue also applies to custom file paths, introduced in #8.

**Comment by nesl247** [comment]
I think the best, at quickest way to resolve this is to either change the current behavior of the root files to be a fallback, or add a fallback to check for the `.github` directory.

I'm not sure about the issue with the other linked ticket though.

**Comment by hiimbex** [comment]
I think the better solution might just be to require the `.github/` folder in the .github repo, no matter what, so the single file permissions can work cleanly.

**Comment by hiimbex** [comment]
But the scenario where it can't read from the .github repo file only happens if the .github is private correct?

So maybe it's easier to just specify the .github repo must public? Unless there's another issue with that solution?

**Comment by nesl247** [comment]
Yes, it only applies to private repositories. The reason it shouldn't require a public repo for a mostly private organization, we don't want anyone submitting PRs against it, we may also have specific settings in there for different bots that shouldn't be viewable outside of the organization.
