### ISSUE TITLE
Use this or context.config()

### ISSUE THREAD

**Issue by BPScott** [probot/probot-config#15]
Probot already has functionality for reading config built into it, [as part of Context](https://github.com/probot/probot/blob/248bf674df06b6dc6b993c6b20482aa0305ef8e2/src/context.ts#L145-L163).

It looks like the original PR in probot added this functionality into core in [May 2017](https://github.com/probot/probot/pull/141), while probot-config was first created in October 2017.

Having two ways to do the same thing is confusing as I don't know which is the blessed way. Which way is the preferred approach? Whichever way is chosen, the other should be removed.

Personally I think this is common enough functionality to earn a place in core. The functionality of this extension should be moved into core and documented and probot-config should be deprecated.

**Comment by hiimbex** [comment]
Great minds think alike! Feel free to throw your thoughts in https://github.com/probot/probot/issues/619!

Closing this out in favor of that!

**Comment by BPScott** [comment]
Thanks for the link @hiimbex
