### ISSUE TITLE
[bug] probot-config returns null, even when defaultConfig is provided

### ISSUE THREAD

**Issue by jbhoosreddy** [probot/probot-config#17]
#### Issue:
In some scenarios, probot-config does not return the defaultConfig and instead return null. As a consumer of this library, our expectation is that probot-config should return defaultConfig instead of null.

```javascript
const getConfig = require('probot-config');

module.exports = robot => {
  robot.on('push', async context => {
    const testConfigDefault = {};
    // Will look for 'test.yml' inside the '.github' folder
    const config = await getConfig(context, 'test.yml', testConfigDefault);
    assert(config !== null, 'config should not be null');
    assert(deepEqual(config, testConfigDefault), 'config should be defaultConfig');
  });
};
```

If the maintainers agree that it's a bug, we could PR something into this project.

**Comment by mheiber** [comment]
Thank you for maintaining probot, we appreciate your help. Any update on this? We'd be happy to PR.

**Comment by jbhoosreddy** [comment]
the line is [here](https://github.com/probot/probot-config/blob/master/lib/index.js#L119).
