### ISSUE TITLE
Release Permission

### ISSUE THREAD

**Issue by hiimbex** [probot/probot-config#24]
Sorry for the swath of pings Sentry folks!! (`bkeepers` is vacationing 🌴), but we recently merged #22 and #16 and would love to get an npm release out reflecting that. Any chance @gr2m and I could get added to the npm package: https://www.npmjs.com/package/probot-config (both our npm logins match our GitHub handles).

cc/ @benvinegar @billyvg @hazat @jan-auer @kamilogorek @mattrobenolt @mitsuhiko

**Comment by jan-auer** [comment]
Done 👍 Thanks for continuing to maintain probot-config so actively!

**Comment by hiimbex** [comment]
Thanks @jan-auer! v1.0.0 is live!
