### ISSUE TITLE
Read from branch that was pushed instead of always master?

### ISSUE THREAD

**Issue by nodesocket** [probot/probot-config#25]
This always seems to pull the config from the master branch. Is there a way to read the config `.github/myApp.yml` from the branch that was pushed instead?

```javascript
module.exports = app => {
    app.on('push', async context => {
        const config = await getConfig(context, 'myApp.yml');
    });
};
````

**Comment by hiimbex** [comment]
You could re-write this module, but that was an explicit decision to always read from master.
