### ISSUE TITLE
(@octokit/rest): `repos.getContent()` is deprecated, use `repos.getContents()`

### ISSUE THREAD

**Issue by nodesocket** [probot/probot-config#27]
Issue appears to be https://github.com/probot/probot-config/blob/master/lib/index.js#L48

**Comment by abhijeetps** [comment]
Probot is still using octokit/restjs `v15.18.0`.
I think `repos.getContents()` is released in `v16.0.0+` of octokit/restjs.

I think by the time probot doesn't use octokit v16.0.0+, we are safe using `repos.getContent()` instead of `repos.getContents()`.

**Comment by hiimbex** [comment]
octokit version 15.18.0 introduced the deprecation warning that caused this, PRs welcome :)

**Comment by abhijeetps** [comment]
Opened a PR, check out #28 😄
