### ISSUE TITLE
path.join results in invalid config path on Windows.

### ISSUE THREAD

**Issue by tplk** [probot/probot-config#9]
I was trying to develop a probot app on Windows 10 (node 10.4.0) and encountered a problem with config fetching. Basically, on Windows `path.join('.github', 'conf.yml')` will return `'.github\conf.yml'` while on Linux it'll be `'.github/conf.yml'`.
Later when passed to octokit backslash will be escaped so resulting path will be `'.github\\conf.yml'` (and request will result in 404).
Is it possible to use something else other than path.join?
For now I'll have to get rid of probot-config and fetch config manually.

**Comment by tplk** [comment]
https://github.com/anodynos/upath will probably do the job to force unix path separators.

**Comment by jan-auer** [comment]
probot-config actually uses `path.posix.join` exactly for that reason:
https://github.com/probot/probot-config/blob/1d4d98dab901c6a9b706b0a2906eda0ba7e68a78/lib/index.js#L100

**Comment by tplk** [comment]
@jan-auer Okay, I see that it was fixed but wasn't released. When is it going to be released on npm?

**Comment by bkeepers** [comment]
0.2.0 was just released, so this should be fixed now!
